// <auto-generated />
using System;
using EstoqueLiaTattoo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueLiaTattoo.Migrations
{
    [DbContext(typeof(EstoqueLiaTattooContext))]
    partial class EstoqueLiaTattooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Agulhas"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Tintas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Descartaveis"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Equipamentos"
                        });
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            IsAtivo = true,
                            Nome = "Agulha 3RL Cartucho",
                            PrecoUnitario = 8.50m,
                            QuantidadeAtual = 25,
                            QuantidadeMinima = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            IsAtivo = true,
                            Nome = "Agulha 7MG Cartucho",
                            PrecoUnitario = 8.50m,
                            QuantidadeAtual = 12,
                            QuantidadeMinima = 5
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            IsAtivo = true,
                            Nome = "Tinta Preta Dynamic 240ml",
                            PrecoUnitario = 190.00m,
                            QuantidadeAtual = 3,
                            QuantidadeMinima = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            IsAtivo = true,
                            Nome = "Tinta Vermelha 140ml",
                            PrecoUnitario = 120.00m,
                            QuantidadeAtual = 2,
                            QuantidadeMinima = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            IsAtivo = true,
                            Nome = "Batoque Descartavel P",
                            PrecoUnitario = 0.05m,
                            QuantidadeAtual = 500,
                            QuantidadeMinima = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            IsAtivo = true,
                            Nome = "Plastico Filme Rolo",
                            PrecoUnitario = 15.00m,
                            QuantidadeAtual = 2,
                            QuantidadeMinima = 2
                        });
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Tinta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PorcentagemRestante")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Tinta");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Material", b =>
                {
                    b.HasOne("EstoqueLiaTattoo.Models.Categoria", "Categoria")
                        .WithMany("Materiais")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Movimentacao", b =>
                {
                    b.HasOne("EstoqueLiaTattoo.Models.Material", "Material")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Tinta", b =>
                {
                    b.HasOne("EstoqueLiaTattoo.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Categoria", b =>
                {
                    b.Navigation("Materiais");
                });

            modelBuilder.Entity("EstoqueLiaTattoo.Models.Material", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
